name: Continuous Integration

# This action works with pull requests and pushes
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Check formatting
        uses: creyD/prettier_action@v4.0
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check functions/**/*.js

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Install modules
        run: cd functions && npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  check-for-errors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Install modules
        run: cd functions && npm install

      - name: Run node
        env:
          GITHUB_ACTION: true
        run: node functions/graphql.js | grep "no errors"
