name: Prettier Check

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - staging
      - main

jobs:
  ESLint and Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Check formatting
        uses: creyD/prettier_action@v4.0
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check functions/**/*.js

      - name: Install modules
        run: cd functions && npm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
